# Generated by Django 5.2 on 2025-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('name', models.CharField(db_index=True, help_text='Product name', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
